port: 7880
rtc:
  tcp_port: 7881
  udp_port: 7882
  # use_external_ip should be true for most cloud environments.
  use_external_ip: true
keys:
  motovoice_key: <ENTER_LIVEKIT_KEY_HERE>
room:
  departure_timeout: 900
  empty_timeout: 900
  max_participants: 20
  # only allow audio
  enabled_codecs:
    - mime: audio/opus
logging:
  level: info
  pion_level: error
