port: 7880
rtc:
  tcp_port: 7881
  port_range_start: 50000
  port_range_end: 60000
  # use_external_ip should be set to true for most cloud environments where
  # the host has a public IP address, but is not exposed to the process.
  # LiveKit will attempt to use STUN to discover the true IP, and advertise
  # that IP with its clients
  use_external_ip: true

room:
  departure_timeout: 900
  empty_timeout: 900
  max_participants: 20
  # only allow audio
  enabled_codecs:
    - mime: audio/opus

# Logging
logging:
  level: info
  pion_level: error
